services:
  app:
    build:
      context: ./app
      target: production
    ports:
      - "3000:80"
    restart: always

  api:
    #build:
    #  context: ./api
    #  target: production
    image: leandrobertoluzzi/cnc-api:latest
    restart: always

  postgresql:
    restart: always

  worker:
    image: leandrobertoluzzi/cnc-worker:latest
    #platform: linux/arm/v7
    volumes:
      # Devices
      - /dev:/dev
      # Devices information
      - /run/udev:/run/udev:ro
