version: "3.8"

services:
  api:
    container_name: remote-cnc-api
    image: remote-cnc-api-image
    depends_on:
      - postgresql
    env_file:
      - api/.env

  app:
    container_name: remote-cnc-app
    image: remote-cnc-app-image

  postgresql:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-datavolume:/var/lib/postgresql/data
    container_name: remote-cnc-postgresql

  adminer:
    image: adminer:4.8.1
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    container_name: remote-cnc-adminer

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    container_name: remote-cnc-redis

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - redis
    ports:
      - 5555:5555
    container_name: remote-cnc-flower

volumes:
  postgres-datavolume:
