version: "3.8"

services:
  app:
    build:
      context: ./app
      target: development
    ports:
      - 3000:3000
    pull_policy: never
    volumes:
      - ./app:/app

  api:
    build:
      context: ./api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  postgresql:
    ports:
      - ${DB_PORT}:5432

  testdb:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=cnc_db
    ports:
      - 5000:5432
    container_name: remote-cnc-testdb
