version: "3.8"

services:
  api:
    container_name: remote-cnc-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: remote-cnc-api-image
    depends_on:
      - mysql
    env_file:
      - api/.env
    networks:
      - frontend
      - backend
    ports:
      - "8000:8000"

  postgresql:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend
    volumes:
      - postgres-datavolume:/var/lib/postgresql/data
    container_name: remote-cnc-postgresql

  adminer:
    image: adminer:4.8.1
    depends_on:
      - postgresql
    networks:
      - backend
    ports:
      - "8080:8080"
    container_name: remote-cnc-adminer

networks:
  frontend:
  backend:

volumes:
  postgres-datavolume:
