version: "3.8"

services:
  app:
    build:
      context: ./app
      target: production
    ports:
      - "3000:80"
    restart: always

  api:
    build:
      context: ./api
      target: production
    restart: always

  postgresql:
    restart: always
