name: remote-cnc

services:
  api:
    container_name: remote-cnc-api
    image: cnc-api
    depends_on:
      - postgresql
    env_file:
      - ./api/.env
      - ./api/core/.env

  app:
    container_name: remote-cnc-app
    image: cnc-app

  postgresql:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-datavolume:/var/lib/postgresql/data
    container_name: remote-cnc-postgresql

  adminer:
    image: adminer:4.8.1
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    container_name: remote-cnc-adminer

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    container_name: remote-cnc-redis

  worker:
    command: celery --app worker worker --loglevel=INFO --logfile=logs/celery.log
    depends_on:
      - redis
      - postgresql
    device_cgroup_rules:
      - 'c 188:* rmw'
    env_file:
      - ./api/core/.env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgresql
    profiles: ["worker"]
    volumes:
      - ./api/gcode_files:/app/gcode_files
      - ./api/core/logs:/app/logs
    container_name: remote-cnc-worker

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - redis
    ports:
      - 5555:5555
    container_name: remote-cnc-flower

volumes:
  postgres-datavolume:
